#ifndef _ROOTCONTROLSETTINGS_H_
#define _ROOTCONTROLSETTINGS_H_

#define TEMPERATURE_THRESHOLD	250
#define TEMPERATURE_HYSTERESIS	20 /*Should be divisible by 4*/

#define HUMIDITY_THRESHOLD	850
#define HUMIDITY_HYSTERESIS	20 /*Should be divisible by 4*/

#define HRS_TURN_ON	6
#define MINS_TURN_ON	0
#define HRS_TURN_OFF	23
#define MINS_TURN_OFF	30



#endif // ROOTCONTROLSETTINGS

